config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/dashboard'

  devise_for :users
  get 'home/index'
  get 'home/get_models_from_brand'
  get 'about_us' => 'home#about_us', :as => :about_us
  get 'contact_us' => 'home#contact', :as => :contact_us
  get 'faq' => 'home#faq', :as => :faq
  get 'privacy' => 'home#privacy_policy', :as => :privacy_policy
  get 'tos' => 'home#tos', :as => :site_tos
  post 'enquiry_mail' => 'home#enquiry_mail'

  resources :users do
    collection do
      get 'myads'
      get 'pending_approval_ads'
      get 'saved_ads'
      put 'remove_saved_ad'
    end
  end

  resources :ads do
    collection do
      get 'get_model'
      get 'model_to_variants'
      get 'success'
      post 'email_to_seller'
      post 'save_ad'
      get :compare
    end
    member do
      get 'tag_spam'
    end
  end

  resources :shortlists do
    member do
      post 'add_ad'
    end
  end

  get 'title_list' => 'ads#title_list'
  get 'location_list' => 'ads#location_list'
  get 'category_list' => 'ads#category_list'

  namespace :api do
    namespace :v1 do
      devise_for :users
      resources :ads, only: [:index, :create] do
        collection do
          post 'show_ad', to: 'ads#show'
        end
        delete :destroy
      end
      resources :users, only: [:dashboard] do
        collection do
          post :dashboard
        end
      end
      get 'brands', to: 'templates#get_brand_names'
      get 'emirates', to: 'templates#get_emirate_names'
      get 'brands/:id', to: 'templates#get_model_names'
      post 'profile_data', to: 'templates#get_profile_data'
      post 'search', to: 'ads#search'
    end
  end

  resources :brands do
    collection do
      get 'get_brands_from_category'
    end
  end

  resources :vehicle_models do
    collection do
      get 'get_vehicle_models_from_brand'
    end
  end

end

app/models/ad.rb
class Ad < ActiveRecord::Base

  searchable do
    float :price
    integer :emirate_id
    boolean :dealer
    boolean :is_approved
    time :created_at
    integer :brand_id do
      vehicle_detail.try(:brand_id)
    end
    integer :vehicle_model_id do
      vehicle_detail.try(:vehicle_model_id)
    end
    integer :mileage do
      vehicle_detail.try(:mileage)
    end
    integer :door_no do
      vehicle_detail.try(:door_no)
    end
    integer :manufacturing_date do
      vehicle_detail.try(:manufacturing_date)
    end
  end

  METHODS_RENDERED = [:emirate_name, :image_path]
  FIELDS_RENDERED = [:id, :name, :title, :location, :description, :price,
                        :created_at, :plan_id, :negotiable, :dealer, :is_approved]
  belongs_to :user
  belongs_to :plan
  belongs_to :country
  belongs_to :emirate
  has_one :seller_information ,dependent: :destroy
  has_one :vehicle_detail, dependent: :destroy
  has_many :photos, as: :imageable ,dependent: :destroy
  # has_many :featured_ads,dependent: :destroy
  paginates_per 10

  accepts_nested_attributes_for :vehicle_detail, :allow_destroy => true
  accepts_nested_attributes_for :photos, :allow_destroy => true
  accepts_nested_attributes_for :seller_information, :allow_destroy => true


  validates :price, numericality: true

  scope :approved, -> { where(is_approved: true) }
  scope :unapproved, -> { where(is_approved: false) }

  def self.dealer_types
    {
      Private: 'private',
      Dealer: 'dealer'
    }
  end

  def as_json(options={})
    super(:methods => Ad::METHODS_RENDERED,
          :include => [
            { :vehicle_detail =>
                {  :only => VehicleDetail::FIELDS_RENDERED }
            },
            { :seller_information =>
                {  :only => SellerInformation::FIELDS_RENDERED }
            }
          ],
          :only => Ad::FIELDS_RENDERED)
  end

  def first_thumb_image
    photos.first.image.url(:thumb) if photos.present?
  end

  def brand_name
    vehicle_detail.try(:brand).try(:name)
  end

  def vehicle_model_name
    vehicle_detail.try(:vehicle_model).try(:name)
  end

  def variant_name
    vehicle_detail.try(:varient).try(:name)
  end

  def seller_name
    seller_information.try(:name).try(:titlecase)
  end

  def image_path
    {
      :original => photos.map{|p| p.image.url},
      :medium => photos.map{|p| p.image.url(:medium)},
      :thumb => photos.map{|p| p.image.url(:thumb)}
    }
  end

  def emirate_name
    emirate.try(:name)
  end

  def created_time
    DateTime.current
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :authenticate_ad_posting , only: [:create,:new]

  def index
    @emirates = Emirate.all
    params[:brand].present? ? @models = VehicleModel.where(brand_id: params[:brand]) : @models = VehicleModel.all
    ads = Ad.search do
      order_by(:created_at, :desc)
      if params[:brand] && params[:brand] != ''
        with(:brand_id, params[:brand])
      end
      if params[:model] && params[:model] != ''
        with(:vehicle_model_id, params[:model])
      end
      if params[:emirate] && params[:emirate] != ''
        with(:emirate_id, params[:emirate])
      end
      if params[:min_price] && params[:min_price] != '' && params[:max_price] && params[:max_price] != ''
        with(:price).between(params[:min_price]..params[:max_price])
      end
      with(:is_approved, true)
      order_by :created_at, :desc
      paginate page: params[:page], :per_page => 10
    end
    @ads = ads.results
  end

  def show
  	@ad = Ad.find_by_id(params[:id])
  end

	def new
		@ad = Ad.new
		@ad.build_vehicle_detail
		@ad.build_seller_information
	end

	def create
		ad = Ad.new(ads_params)
		ad.ad_type = "sell"
    ad.seller_information.email = "anonymousabc.com" if ad.seller_information.email == "Anonymous"
    ad.name = Brand.where(
      id: params[:ad][:vehicle_detail_attributes][:brand_id]).first.try(:name) + " " +
      VehicleModel.where(id: params[:ad][:vehicle_detail_attributes][:vehicle_model_id])
      .first.try(:name)
		ad.user_id = current_user.id
    ad.is_approved = false
    ad.state = 'initiated'
		if ad.save
			if params[:photos]
	        params[:photos].each { |image|
	          ad.photos.create(image: image)
	        }
	      end
	  end
    redirect_to :success_ads
	end

  def success
  end

  def destroy
  	ad = current_user.ads.where(id: params[:id]).first
  	ad.destroy
  	render :json => { }
  end

  def title_list
    list = Ad.approved.collect {|ad| {:id => ad.title,:name => "#{ad.title}" }}.compact.uniq
    render :json => list
  end

  def category_list
    list = Ad.categories.collect {|category| {:id => category[0],:name => category[1] }}
    render :json => list
  end

  def location_list
    list = Ad.approved.collect {|ad| {:id => ad.location,:name => "#{ad.location}" }}.compact.uniq
    render :json => list
  end

  def email_to_seller
    UserMailer.email_to_seller(params[:ad_id],params[:to_mail],params[:seller_name],params[:sender_name],params[:sender_email],params[:recipient_phone_number],params[:message_text]).deliver_later
    respond_to do |format|
      format.js { render layout: false, content_type: 'text/javascript' }
    end
  end

	def get_model
		models = Brand.find(params[:id]).vehicle_models.pluck(:id,:name)
		initial_variant = Variant.where(vehicle_model_id: models.first[0]).pluck(:id, :name)
    respond_to do |format|
    	format.json {render json: {models: models, initial_variant: initial_variant}}
    end
	end

  def authenticate_ad_posting
    flash[:notice] = "Please login to post free advertisement." unless signed_in?
    authenticate_user!
  end

  def save_ad
    short_lists = Shortlist.where(ad_id: params[:id],user_id:params[:user_id])
    if short_lists.present?
      @message ='Already short listed'
      respond_to do |format|
        format.js { render layout: false, content_type: 'text/javascript' }
      end
    else
      Shortlist.create(ad_id: params[:id],user_id:params[:user_id])
      @message='Successfully short listed'
      respond_to do |format|
        format.js { render layout: false, content_type: 'text/javascript' }
      end
    end
  end

  def tag_spam
    if current_user.nil?
      @result = 'nologin'
    else
      Spam.create(user_id: current_user.id, ad_id: params[:ad_id])
    end
    respond_to do |format|
      format.js
    end
  end

  def compare
    ads_cookies = JSON.parse(cookies[:ads_to_compare])
    if ads_cookies.count < 4 && ads_cookies.count > 1
      ad_ids_to_compare = ads_cookies.map{|a| a['id']}
    elsif ads_cookies.count < 2
      flash[:alert] = 'Select minimum of 2 ads or maximum of 3 ads for comparison !'
      redirect_to ads_path
    end
    @ads = Ad.where(id: ad_ids_to_compare)
    @ad1 = @ads.first
    @ad2 = @ads.last(2).first
    @ad3 = @ads.last if @ads.count > 2
  end

private

	def ads_params
    params.require(:ad).permit(:type, :category_id, :country_id, :emirate_id, :location,
      :phone, :status, :description, :price, :negotiable,
      :name, :title, :dealer,
    vehicle_detail_attributes: [:id, :brand_id,
      :vehicle_model_id, :variant_id, :manufacturing_date, :mileage, :fuel, :color,
      :insurance_date, :owner_count, :_destroy, :door_no, :cylinder, :capacity,
      :regional_spec, :horse_power, :cruise_control, :navigation, :fourwheel_drive,
      :allwheel_drive, :body_kit, :climate_control, :keyless_entry, :keyless_start,
      :radio, :aux_audio, :offroad_kit, :offroad_tyre, :parking_sensor, :moonroofs,
      :cd_player, :dvd_player, :power_mirror, :power_seats, :power_sunroof,
      :power_windows, :premium_lights, :premium_paint, :premium_soundsystem,
      :premium_wheels, :racing_seats, :roof_rack, :satellite_radio, :spoiler, :sunroof,
      :winch, :dual_exhaust, :power_steering, :n2o, :tiptronic_gears, :brush_guard,
      :heated_seats, :heat, :cooled_seats, :transmission, :abs, :front_airbags,
      :side_airbags, :bluetooth, :alarm_antitheft],
     seller_information_attributes: [:name, :email, :phone_number])
  end

end

app/controllers/api/v1/ads_controller.rb
class Api::V1::AdsController < Api::V1::BaseController

  def index
    render status: :ok, json: {
      message: 'Go through the new API changes.'
    }
  end

  def create
    ad = Ad.new(ads_params)
    ad.ad_type = 'sell'
    ad.name = generate_name
    ad.seller_information.email = seller_email
    ad.is_approved = false
    ad.state = 'initiated'
    ad.user_id = current_user.id
    if ad.save
      if params[:photos]
          params[:photos].each { |image|
            ad.photos.create(image: image)
          }
      end
      render json: {
        message: 'Successful, wait until verification.'
      }
    else
      render json: {
        message: 'Failed, check your inputs'
      }
    end
  end

  def show
    ad = Ad.find_by(id: params[:id])
    if ad.present?
      render json: { ad: ad }
    else
      render json: { message: 'No ad found !' }
    end
  end

  def search
    search_ads = Ad.search do
      if params[:brand] && params[:brand] != ''
        with(:brand_id, params[:brand])
      end
      if params[:model] && params[:model] != ''
        with(:vehicle_model_id, params[:model])
      end
      if params[:emirate] && params[:emirate] != ''
        with(:emirate_id, params[:emirate])
      end
      if params[:min_price] && params[:min_price] != '' && params[:max_price] && params[:max_price] != ''
        with(:price).between(params[:min_price]..params[:max_price])
      end
      with(:is_approved, true)
      order_by :created_at, :desc
      paginate page: params[:page], per_page: 10
    end
    ads = search_ads.results
    if ads.present?
      render json: {
        ads: ads, pages: ads.total_pages
      }
    else
      render json: {
      message: 'No ads found !'
    }
    end
  end

  def destroy
    ad = current_user.ads.where(id: params[:ad_id]).first
    if ad.destroy
      render json: {
        message: 'Successfully deleted.'
      }
    else
      render json: {
        message: 'Failed, try again !'
      }
    end
  end

  private

  def seller_email
    email = ads_params[:seller_information_attributes][:email]
    if email.nil? || email == 'Anonymous'
      'anonymous@abc.com'
    else
      email
    end
  end

  def generate_name
    Brand.where(id: ads_params[:vehicle_detail_attributes][:brand_id]).first.try(:name) + ' ' +
    VehicleModel.where(id: ads_params[:vehicle_detail_attributes][:vehicle_model_id]).first.try(:name)
  end

  def ads_params
    params.require(:ad).permit(:type, :category_id, :country_id, :emirate_id, :location,
      :phone, :status, :description, :price, :negotiable,
      :name, :title, :dealer,
    vehicle_detail_attributes: [:id, :brand_id,
      :vehicle_model_id, :variant_id, :manufacturing_date, :mileage, :fuel, :color,
      :insurance_date, :owner_count, :_destroy, :door_no, :cylinder, :capacity,
      :regional_spec, :horse_power, :cruise_control, :navigation, :fourwheel_drive,
      :allwheel_drive, :body_kit, :climate_control, :keyless_entry, :keyless_start,
      :radio, :aux_audio, :offroad_kit, :offroad_tyre, :parking_sensor, :moonroofs,
      :cd_player, :dvd_player, :power_mirror, :power_seats, :power_sunroof,
      :power_windows, :premium_lights, :premium_paint, :premium_soundsystem,
      :premium_wheels, :racing_seats, :roof_rack, :satellite_radio, :spoiler, :sunroof,
      :winch, :dual_exhaust, :power_steering, :n2o, :tiptronic_gears, :brush_guard,
      :heated_seats, :heat, :cooled_seats, :transmission, :abs, :front_airbags,
      :side_airbags, :bluetooth, :alarm_antitheft],
     seller_information_attributes: [:name, :email, :phone_number])
  end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/views/ads/email_to_seller.js.erb
 $('.modal .close').click();

app/views/ads/index.html.erb
<%= form_tag(ads_path, method: :get) do %>
  <div class="search-row-wrapper">
    <div class="container ">
      <div class="col-sm-3">
        <%= select_tag 'emirate', options_from_collection_for_select(Emirate.all, "id", "name", params[:emirate]),  { class: 'form-control emirate', prompt: 'City (All)' } %>
      </div>
      <div class="col-sm-3">
        <%= select_tag :brand, options_from_collection_for_select(Brand.all, "id", "name", params[:brand]), { class: 'form-control', prompt: 'Brand (All)' } %>
      </div>
      <div class="col-sm-3">
        <%= select_tag :model, options_from_collection_for_select(@models,"id", "name", params[:model]), { class: 'form-control', prompt: 'Model (All)' } %>
      </div>
      <div class="col-sm-3">
        <%= button_tag type: 'submit', class: "btn btn-block btn-primary" do %>
          <i class="fa fa-search"></i> <strong> Find </strong>
        <% end %>
      </div>
    </div>
  </div>
    <div class="main-container">
      <div class="container">
         <div class="row">
            <div class="col-sm-3 col-sm-pull-1 page-sidebar">
               <aside>
                  <div class="inner-box">
                     <div class="locations-list  list-filter">
                        <h5 class="list-title"><strong><a href="#">Price range</a></strong></h5>
                           <div class="form-group col-sm-4 no-padding" style="margin-right: 5px;">
                              <%= number_field_tag :min_price, nil, min: 100, max: 9999999, class: "form-control", placeholder: 'From', style: 'width: 150%;' %>
                           </div>
                           <div class="form-group col-sm-1 no-padding text-center"></div>
                           <div class="form-group col-sm-4 no-padding">
                              <%= number_field_tag :max_price, nil, min: 100, max: 9999999, class: "form-control", placeholder: 'To', style: 'width: 150%; margin-left: 16px;' %>
                           </div>
                        <div style="clear:both"></div>
                     </div>
                     <div class="locations-list  list-filter">
                        <h5 class="list-title"><strong><a href="#">Build Year</a></strong></h5>
                        <ul class="browse-list list-unstyled long-list">
                          <li>
                           <div class="form-group col-sm-4 no-padding">
                              <%= select_tag :build_start, options_for_select(2000..2016), class: "form-control", prompt: 'From', style: 'width: 150%;' %>
                           </div>
                           <div class="form-group col-sm-1 no-padding text-center"> - </div>
                           <div class="form-group col-sm-4 no-padding">
                              <%= select_tag :build_end, options_for_select(2000..2016), class: "form-control", prompt: 'Till', style: 'width: 150%;' %>
                          </li>
                        </ul>
                     </div>
                     <div style="clear:both"></div>
                     <div class="locations-list  list-filter">
                        <h5 class="list-title"><strong><a href="#">Mileage</a></strong></h5>
                        <ul class="browse-list list-unstyled long-list">
                          <li>
                           <div class="form-group col-sm-4 no-padding">
                              <%= number_field_tag :mileage_from, nil, min: 100, max: 9999999, class: "form-control", placeholder: 'From', style: 'width: 150%;' %>
                           </div>
                           <div class="form-group col-sm-1 no-padding text-center"> - </div>
                           <div class="form-group col-sm-4 no-padding">
                              <%= number_field_tag :mileage_to, nil, min: 0, max: 9999999, class: "form-control", placeholder: 'Till', style: 'width: 150%;' %>
                          </li>
                        </ul>
                     </div>
                     <div style="clear:both"></div>
                     <div class="locations-list  list-filter">
                        <h5 class="list-title"><strong><a href="#">No. of Doors</a></strong></h5>
                        <ul class="browse-list list-unstyled long-list">
                          <li>
                           <div class="form-group col-sm-4 no-padding">
                              <%= select_tag :door_no, options_for_select([4,2]), class: "form-control", prompt: 'All' %>
                           </div>
                          </li>
                        </ul>
                     </div>
                     <div style="clear:both"></div>
                     <div class="locations-list  list-filter">
                        <h5 class="list-title"><strong><a href="#">Seller Type</a></strong></h5>
                        <ul class="browse-list list-unstyled long-list">
                          <li>
                           <div class="form-group col-sm-4 no-padding">
                              <%= select_tag :dealer, options_for_select(Ad.dealer_types), { class: 'form-control', prompt: 'All' } %>
                           </div>
                          </li>
                        </ul>
                     </div>
                     <div style="clear:both"></div>
                     <div class="locations-list  list-filter">
                      <%= button_tag type: 'submit', class: "btn btn-block btn-primary" do %>
                      <i class="fa fa-search"></i> <strong> Find </strong>
                      <% end %>
                     </div>
                     <div style="clear:both"></div>
                  </div>
               </aside>
            </div>
            <div class="col-sm-9 col-sm-pull-1 page-content col-thin-left">
               <div class="category-list">
    <!--               <div class="tab-box ">
                     <ul class="nav nav-tabs add-tabs" id="ajaxTabs" role="tablist">
                        <li class="active"><a>All Ads <span class="badge"><%=@ads_count %></span></a></li>
                     </ul>
                  </div>
                  <div class="listing-filter">
                     <div class="pull-left col-xs-6">
                        <div class="breadcrumb-list">
                        <a href="#" class="current">
                        <span>All ads</span></a> in New York <a href="#selectRegion" id="dropdownMenu1" data-toggle="modal"> <span class="caret"></span> </a> </div>
                     </div>
                     <div class="pull-right col-xs-6 text-right listing-view-action"> <span class="list-view active"><i class="  icon-th"></i></span> <span class="compact-view"><i class=" icon-th-list  "></i></span> <span class="grid-view "><i class=" icon-th-large "></i></span> </div>
                     <div style="clear:both"></div>
                  </div> -->
                  <div class="adds-wrapper">
                     <div class="tab-content">
                          <div class="tab-pane active" id="allAds">
                          <% if @ads.blank? %>
                            <h2 class='text-center' style="padding-top: 14px;"> No ads to show !</h2>
                          <% else %>
                            <% @ads.each do |ad| %>
                              <div class="item-list">
    <!--                        <div class="cornerRibbons topAds">
                                   <a href="#"> Top Ads</a>
                                </div> -->
                                <div class="col-sm-2 no-padding photobox">
                                  <div class="add-image">
                                    <span class="photo-count"><i class="fa fa-camera"></i> <%= ad.photos.count %>
                                    </span>
                                    <a href="<%= ad_path(ad) %>"><%= image_tag ad.photos.first.image.url(:thumb), class:"thumbnail no-margin ad-image-dp" if ad.photos.present? %>
                                   </a> </div>
                                </div>
                                <div class="col-sm-7 add-desc-box">
                                   <div class="add-details">
                                      <h5 class="add-title"> <a href="<%= ad_path(ad) %>">
                                        <div id=<%= "name_#{ad.id}" %>>
                                          <%= ad.name %> </a>
                                        </div>
                                      </h5>
                                      <div class="title-block">
                                        <i> <%= "\"#{ad.title}\"" if ad.title %></i>
                                      </div>
                                      <span class="info-row">
                                        <span class="ad-detail-span date" title="Posting time"><i class="fa fa-clock-o fa-2x"> </i> <%= time_ago_in_words(ad.created_at) %> </span>
                                          <span class="ad-detail-span item-location" title="Location"><i class="fa fa-map-marker fa-2x"></i> <%=
                                          ad.location.present? ? ad.location.try(:humanize) : 'N/A' %></span>
                                      </span>
                                      <span class="info-row">
                                          <span class="ad-detail-span item-mileage" title="Mileage"><i class="fa fa-tachometer fa-2x"></i>
                                          <%= ad.vehicle_detail.mileage.present? ? number_with_delimiter(ad.vehicle_detail.mileage) + " Kms" : 'N/A'
                                           %> </span>
                                          <span class="ad-detail-span item-build" title="Build date"><i class="fa fa-calendar fa-2x"></i> <%= ad.vehicle_detail.manufacturing_date.present? ? ad.vehicle_detail.manufacturing_date.try(:humanize) : 'N/A' %></span>
                                          <span class="ad-detail-span item-engine" title="Engine power"><i><%= image_tag("engine.png") %></i>
                                          <%= ad.vehicle_detail.cylinder.present?||ad.vehicle_detail.capacity.present? ? "#{ad.vehicle_detail.cylinder}cyl #{ad.vehicle_detail.capacity}L" : 'N/A' %>
                                          </span>
                                      </span>
                                   </div>
                                </div>
                                <div class="col-sm-3 text-right price_box">
                                  <% if ad.negotiable %>
                                    Negotiable  <i class="fa fa-check"></i>
                                  <% else %>
                                    Negotiable  <i class="fa fa-times"></i>
                                  <% end %>
                                    <h2 class="item-price"> AED  <%= number_with_delimiter(ad.price) %> </h2>
                                    <%= link_to "View", ad_path(ad), class: 'btn btn-primary' %>
                                    <%= link_to "Compare", '', class: 'btn btn-primary compare_btn', id: ad.id %>
                                    <%= link_to'', class: 'btn btn-danger save_ad' do %>
                                      <i class="fa fa-gratipay" aria-hidden="true"></i>
                                    <% end %>
                                </div>
                              </div>
                            <% end %>
                          <% end %>
                        </div>
                     </div>
                  </div>
               </div>
               <% unless @ads.blank? %>
                 <div class="pagination-bar text-center">
                  <%= paginate @ads %>
                 </div>
              <% end %>
               <div class="post-promo text-center">
                  <h2> Do you get anything for sell ? </h2>
                  <h5>Buy/Sell vehicles online FOR FREE. It's easier than you think !</h5>
                  <a href="<%= new_ad_path %>" class="btn btn-lg btn-border btn-post btn-danger" data-no-turbolink>Post a Free Ad </a>
               </div>
            </div>
         </div>
      </div>
  </div>
<% end %>
<div class='compare_box' style='display: none;'>
  <div class="panel panel-default">
    <div class="panel-heading">Selected items for comparison</div>
    <div class="panel-body">
      <ol class='compare_ol'>
      </ol>
    </div>
    <div class='compare_box_btn'><%= link_to "Compare", compare_ads_path,
                                              class: 'btn btn-primary', id: 'compare_ads' %></div>
  </div>
</div>

app/views/ads/save_ad.js.erb
alert('<%= @message%>');

app/views/ads/success.html.erb
<div class="main-container">
  <div class="container">
    <div class="row">
      <div class="col-md-12 page-content">
        <div class="inner-box category-content">
          <div class="row">
            <div class="col-lg-12">
              <div class="alert alert-success pgray  alert-lg" role="alert">
                <h2 class="no-margin no-padding">&#10004; Congratulations! Your ad will be published soon.</h2>
                <p>Please wait until review completes. You can check status of review in your dashboard.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/ads/tag_spam.js.erb
<% if @result == 'nologin' %>
  $('#alert').text('You are not logged in, please login to report ads.').attr('class', 'alert alert-info pgray  alert-lg');
<% else %>
  $('#alert').text('Ad has been successfully reported. Thanks for the reporting.').attr('class', 'alert alert-info pgray  alert-lg');
  $('#alert').show();
  $('#report_link').click(function () {return false;});
<% end %>
$('#alert').show();