config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/dashboard'

  devise_for :users
  get 'home/index'
  get 'home/get_models_from_brand'
  get 'about_us' => 'home#about_us', :as => :about_us
  get 'contact_us' => 'home#contact', :as => :contact_us
  get 'faq' => 'home#faq', :as => :faq
  get 'privacy' => 'home#privacy_policy', :as => :privacy_policy
  get 'tos' => 'home#tos', :as => :site_tos
  post 'enquiry_mail' => 'home#enquiry_mail'

  resources :users do
    collection do
      get 'myads'
      get 'pending_approval_ads'
      get 'saved_ads'
      put 'remove_saved_ad'
    end
  end

  resources :ads do
    collection do
      get 'get_model'
      get 'model_to_variants'
      get 'success'
      post 'email_to_seller'
      post 'save_ad'
      get :compare
    end
    member do
      get 'tag_spam'
    end
  end

  resources :shortlists do
    member do
      post 'add_ad'
    end
  end

  get 'title_list' => 'ads#title_list'
  get 'location_list' => 'ads#location_list'
  get 'category_list' => 'ads#category_list'

  namespace :api do
    namespace :v1 do
      devise_for :users
      resources :ads, only: [:index, :create] do
        collection do
          post 'show_ad', to: 'ads#show'
        end
        delete :destroy
      end
      resources :users, only: [:dashboard] do
        collection do
          post :dashboard
        end
      end
      get 'brands', to: 'templates#get_brand_names'
      get 'emirates', to: 'templates#get_emirate_names'
      get 'brands/:id', to: 'templates#get_model_names'
      post 'profile_data', to: 'templates#get_profile_data'
      post 'search', to: 'ads#search'
    end
  end

  resources :brands do
    collection do
      get 'get_brands_from_category'
    end
  end

  resources :vehicle_models do
    collection do
      get 'get_vehicle_models_from_brand'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  validates_presence_of :first_name

  before_create :generate_authentication_token

  has_many :shortlists,dependent: :destroy
  has_many :ads, dependent: :destroy

  def name
  	"#{first_name} #{last_name}"
  end

  def last_login
  	last_sign_in_at.strftime("%d-%m-%Y %H:%M:%S [%z %Z]")
  end

  def ensure_authentication_token!
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

  private

  def generate_authentication_token
    self.authentication_token = SecureRandom.base64(64)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  def dashboard
    my_ads = current_user.ads
    pending_ads = current_user.ads.unapproved
    short_list_ads = Shortlist.where(user_id:current_user.id)
    if my_ads.present?
      render json: {
        my_ads: my_ads,
        pending_ads: pending_ads,
        short_list_ads: short_list_ads
      }
    else
      render json: {
        message: 'No ad found !'
      }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

  def dashboard
    @my_ads = current_user.ads
    ad_counts
  end

  def update
    @user = current_user
  	 if @user.update(user_params)
  	 	flash[:notice] = 'Sucessfully updated details !'
  	 else
  	 	flash[:alert] = @user.errors.full_messages.to_sentence
  	 end
    redirect_to users_dashboard_path
  end

  def myads
    @my_ads = current_user.ads
    ad_counts
  end

  def pending_approval_ads
    @my_ads = current_user.ads.unapproved
    ad_counts
  end

  def saved_ads
    short_list_ids = Shortlist.where(user_id:current_user.id).pluck(:ad_id)
    @my_ads = Ad.where(id: short_list_ids)
    ad_counts
  end

  def remove_saved_ad
    ad = Shortlist.find_by_ad_id(params[:id])
    ad.destroy
    render :json => { }
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:notice] = 'Account is removed'
    redirect_to root_path
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :address, :phone, :emirate_id, :city, :password,
                                 :password_confirmation, :newsletter, :mail_com, :location)
  end

  def ad_counts
    @my_ads_count = current_user.ads.count
    @ad_pending_count = current_user.ads.unapproved.count
    @short_list_count = Shortlist.where(user_id:current_user.id).count
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_ad_list.html.erb
<table id="addManageTable" class="table table-striped table-bordered add-manage-table table demo" data-filter="#filter" data-filter-text-only="true">
  <thead>
    <tr>
      <th> Photo </th>
      <th data-sort-ignore="true"> Details </th>
      <th> Status </th>
      <th> Action </th>
    </tr>
  </thead>
  <tbody>
    <% @my_ads.each do |ad| %>
      <tr>
        <!-- <td style="width:2%" class="add-img-selector">
          <div class="checkbox">
            <label>
              <input type="checkbox">
            </label>
          </div>
        </td> -->
        <td style="width:14%" class="add-img-td">
          <a href="<%= ad_path(ad) %>">
          <%= image_tag ad.first_thumb_image, class:"thumbnail  img-responsive" %>
          </a>
        </td>
        <td style="width:58%" class="ads-details-td">
          <div>
            <p><strong> <a href="<%= ad_path(ad) %>" title="Brend New Nexus 4"><%= ad.title%></a> </strong></p>
            <p> <strong> Posted On </strong>:
            <%= time_ago_in_words(ad.created_at) %> </p>
            <p><strong>Located In:</strong> <%= ad.location %> </p>
            <p><strong>Listed price:</strong>  AED <%=  number_with_delimiter(ad.price) %> </p>
          </div>
        </td>
        <td style="width:16%" class="price-td">
          <div><strong><%= ad.is_approved ? 'Active' :  'Unapproved' %></strong></div>
        </td>
        <td style="width:10%" class="action-td">
          <div>
            <!-- <p>
              <a class="btn btn-primary btn-xs"> <i class="fa fa-edit"></i> Edit </a>
            </p> -->
            <p>
              <a class="btn btn-info btn-xs"> <i class="fa fa-mail-forward"></i> Share </a>
            </p>
            <%if params[:action]=='saved_ads' %>
              <p>
                <a class="btn btn-danger btn-xs remove-saved_ad-btn" id='<%=ad.id%>'> <i class=" fa fa-trash"></i> Remove </a>
              </p>
            <% else %>
              <p>
                <a class="btn btn-danger btn-xs delete-ad-btn" id='<%=ad.id%>'> <i class=" fa fa-trash"></i> Delete </a>
              </p>
            <%end%>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_dashboard_notice.html.erb
<% if !flash[:user_update_success].blank? %>
    <p class="alert alert-success  pgray  alert-lg role='alert'"><%= flash[:user_update_success] %></p>
 <% elsif !flash[:user_update_warning].blank? %>
 	 <p class="alert alert-warning pgray  alert-lg role='alert'"><%= flash[:user_update_warning] %></p>
<% end %>

app/views/users/_user_sidebar.html.erb
<!-- Use active class to activate pane. -->
<div class="inner-box">
  <div class="user-panel-sidebar">
    <div class="collapse-box">
      <h5 class="collapse-title no-border">Dashboard
      <a class="pull-right fa fa-angle-down" data-toggle=
      "collapse" href="#MyClassified" style=
      "font-style: italic"></a></h5>
      <div class="panel-collapse collapse in" id="MyClassified">
        <ul class="acc-list">
          <li>
            <a href="<%= users_dashboard_path %>"><i class=
            "icon-home"></i> Personal settings</a>
          </li>
        </ul>
      </div>
    </div>
      <h5 class="collapse-title">My Ads <a class=
      "pull-right fa fa-angle-down" data-toggle="collapse" href=app/views/devise/passwords/new.html.erb
      "#MyAds" style="font-style: italic"></a></h5>
      <div class="panel-collapse collapse in" id="MyAds">
        <ul class="acc-list">
          <li>
            <a href="<%= myads_users_path %>"><i class=
            "icon-docs"></i> My Ads  <span class=
            "badge"><%= @my_ads_count %></span></a>
          </li>
          <!-- <li>
            <a href="account-saved-search.html"><i class=
            "icon-star-circled"></i> Saved search <span class=
            "badge">42</span></a>
          </li>
          <li>
            <a href="account-archived-ads.html"><i class=
            "icon-folder-close"></i> Archived ads <span class=
            "badge">42</span></a>
          </li> -->
          <li>
            <a href="<%= pending_approval_ads_users_path %>"><i class=
            "icon-hourglass"></i> Pending approval <span class=
            "badge"><%= @ad_pending_count %></span></a>
          </li>
          <li>
            <a href="<%=saved_ads_users_path%>"><i class=
            "icon-heart"></i> Saved Ads  <span class=
            "badge"><%= @short_list_count %></span></a>
          </li>
        </ul>
    </div>
  </div>
  <div class="collapse-box">
    <h5 class="collapse-title">Terminate Account <a class=
    "pull-right fa fa-angle-down" data-toggle="collapse" href=
    "#TerminateAccount" style="font-style: italic"></a></h5>
    <div class="panel-collapse collapse in" id=
    "TerminateAccount">
      <ul class="acc-list">
        <li>
          <a href="<%= user_path(current_user) %>" data-confirm= 'Are you sure?' data-method='delete'><i class=
          "icon-cancel-circled"></i> Close account</a>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="main-container">
      <div class="container">
        <div class="row">
          <div class="col-sm-3 page-sidebar">
            <aside>
              <%= render 'user_sidebar' %>
            </aside>
          </div>
          <div class="col-sm-9 page-content">
            <div class="inner-box">
              <div class="row">
                <div class="col-md-5 col-xs-4 col-xxs-12">
                  <h3 class="no-padding text-center-480 useradmin"><a href=
                  "">
                  <%= image_tag("default-profile.png", :class => "userImg") %>
                  <%= current_user.name %></a></h3>
                </div>
                <div class="col-md-7 col-xs-8 col-xxs-12">
                  <div class="header-data text-center-xs">

                    <div class="hdata">
                      <div class="mcol-left">
                        <i class="icon-th-thumb ln-shadow"></i>
                      </div>
                      <div class="mcol-right">
                        <p><a href="#"><%= @my_ads_count %> </a><em>Ads</em></p>
                      </div>
                      <div class="clearfix"></div>
                    </div>
                    <!-- <div class="hdata">
                      <div class="mcol-left">
                        <i class="fa fa-user ln-shadow"></i>
                      </div>
                      <div class="mcol-right">
                        <p><a href="#">18</a> <em>Favorites</em></p>
                      </div>
                      <div class="clearfix"></div>
                    </div> -->
                  </div>
                </div>
              </div>
            </div>
            <div class="inner-box">
              <div class="welcome-msg">
                <h3 class="page-sub-header2 clearfix no-padding">Hello 
                <%= current_user.name %>
                </h3><span class="page-sub-header-sub small">Your last login time was <%= time_ago_in_words(current_user.last_login) %> ago </span>
              </div>
              <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title"><a data-toggle="collapse" href=
                    "#collapseB1">Profile</a></h4>
                  </div>
                  
                   <div class="panel-collapse collapse in" id="collapseB1">
                    <div class="panel-body">
                      <!-- <form class="form-horizontal" role="form"> -->
                      <%= form_for(current_user, html: { method: :put, class: "form-horizontal" }) do |f| %>
                        <div class="form-group">
                          <label class="col-sm-3 control-label">First
                          Name</label>
                          <div class="col-sm-9">
                            <%= f.text_field :first_name, class: "form-control" %>
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="col-sm-3 control-label">Last
                          name</label>
                          <div class="col-sm-9">
                          	<%= f.text_field :last_name, class: "form-control" %>
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="col-sm-3 control-label">Email</label>
                          <div class="col-sm-9">
                          	<%= f.email_field :email, class: "form-control" %>
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="col-sm-3 control-label">Location</label>
                          <div class="col-sm-9">
                          <%= f.text_area :location, class: "form-control" %>
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="col-sm-3 control-label" for=
                          "Phone">Phone</label>
                          <div class="col-sm-9">
                          	<%= f.text_field :phone, class: "form-control" %>
                          </div>
                        </div>
                        <!-- <div class="form-group hide">
                          <label class="col-sm-3 control-label">Facebook
                          account map</label>
                          <div class="col-sm-9">
                            <div class="form-control">
                              <a class="link" href="fb.com">Jhone.doe</a>
                              <a class="fa fa-minus-circle" class="" style=
                              "font-style: italic"></a>
                            </div>
                          </div>
                        </div> -->
                        <div class="form-group">
                          <div class="col-sm-offset-3 col-sm-9"></div>
                        </div>
                        <div class="form-group">
                          <div class="col-sm-offset-3 col-sm-9">
                            <%= f.submit "Update", class: "btn btn-success" %>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title"><a data-toggle="collapse" href=
                    "#collapseB2">Password</a></h4>
                  </div>
                  <div class="panel-collapse collapse" id="collapseB2">
                    <div class="panel-body">
                    <span class="page-sub-header-sub small">
                      You'll be signed out once you successfully change your password !
                    </span>
                    <br><br>
                      <%= form_for(current_user, html: { method: :put, class: "form-horizontal" }) do |f| %>
                      <form class="form-horizontal" role="form">
                        <div class="form-group">
                          <label class="col-sm-3 control-label">New
                          Password</label>
                          <div class="col-sm-9">
                            <%= f.password_field :password, class: "form-control" %>
                          </div>
                        </div>
                        <div class="form-group">
                          <label class="col-sm-3 control-label">Confirm
                          Password</label>
                          <div class="col-sm-9">
                          <%= f.password_field :password_confirmation, class: "form-control" %>
                          </div>
                        </div>
                        <br>
                        <div class="form-group">
                          <div class="col-sm-offset-3 col-sm-9">
                            <%= f.submit "Update", class: "btn btn-success" %>
                            <% end %>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title"><a data-toggle="collapse" href=
                    "#collapseB3">Mail Preferences</a></h4>
                  </div>
                  <div class="panel-collapse collapse" id="collapseB3">
                    <div class="panel-body">
	                      <%= form_for(current_user, html: { method: :put, class: "form-horizontal" }) do |f| %>
	                      <div class="form-group">
	                        <div class="col-sm-12">
	                          <div class="checkbox">
	                            <%= f.check_box :newsletter %>
	                            <%= f.label 'I want to receive occasional newsletters' %>
	                          </div>
	                          <div class="checkbox">
	                            <%= f.check_box :mail_com %>
	                            <%= f.label 'Notifications about my posted ads and wish list.' %>
	                          </div>
                            <br>
	                          <div class="form-group">
                          		<div class="col-sm-offset-3 col-sm-9">
                            		<%= f.submit "Update", class: "btn btn-success" %>
                          		</div>
                        		</div>
	                        </div>
	                      <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

app/views/users/myads.html.erb
    <div class="main-container">
      <div class="container">
        <div class="row">
          <div class="col-sm-3 page-sidebar">
            <aside>
              <%= render 'user_sidebar' %>
            </aside>
          </div>
          <div class="col-sm-9 page-content">
            <div class="inner-box">
              <h2 class="title-2"><i class="icon-docs"></i>My Advertisements</h2>
                <h3><p> Advertisements posted by me.</p></h3>
                <div class="table-responsive">
                  <%= render 'ad_list' %>
                </div>
            </div>
          </div>
      </div>
    </div>
  </div>

app/views/users/pending_approval_ads.html.erb
<div class="main-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-3 page-sidebar">
        <aside>
          <%= render 'user_sidebar' %>
        </aside>
      </div>
      <div class="col-sm-9 page-content">
        <div class="inner-box">
          <h2 class="title-2"><i class="icon-hourglass"></i>  Pending approval </h2>
          <h3><p> Advertisements waiting to be approved by admin.</p></h3>
          <div class="table-responsive">
            <%= render 'ad_list' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/saved_ads.html.erb
    <div class="main-container">
      <div class="container">
        <div class="row">
          <div class="col-sm-3 page-sidebar">
            <aside>
              <%= render 'user_sidebar' %>
            </aside>
          </div>
          <div class="col-sm-9 page-content">
            <div class="inner-box">
              <h2 class="title-2"><i class="icon-docs"></i>My Advertisements</h2>
                <h3><p> Advertisements saved by me.</p></h3>
                <div class="table-responsive">
                  <%= render 'ad_list' %>
                </div>
            </div>
          </div>
      </div>
    </div>
  </div>