config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/dashboard'

  devise_for :users
  get 'home/index'
  get 'home/get_models_from_brand'
  get 'about_us' => 'home#about_us', :as => :about_us
  get 'contact_us' => 'home#contact', :as => :contact_us
  get 'faq' => 'home#faq', :as => :faq
  get 'privacy' => 'home#privacy_policy', :as => :privacy_policy
  get 'tos' => 'home#tos', :as => :site_tos
  post 'enquiry_mail' => 'home#enquiry_mail'

  resources :users do
    collection do
      get 'myads'
      get 'pending_approval_ads'
      get 'saved_ads'
      put 'remove_saved_ad'
    end
  end

  resources :ads do
    collection do
      get 'get_model'
      get 'model_to_variants'
      get 'success'
      post 'email_to_seller'
      post 'save_ad'
      get :compare
    end
    member do
      get 'tag_spam'
    end
  end

  resources :shortlists do
    member do
      post 'add_ad'
    end
  end

  get 'title_list' => 'ads#title_list'
  get 'location_list' => 'ads#location_list'
  get 'category_list' => 'ads#category_list'

  namespace :api do
    namespace :v1 do
      devise_for :users
      resources :ads, only: [:index, :create] do
        collection do
          post 'show_ad', to: 'ads#show'
        end
        delete :destroy
      end
      resources :users, only: [:dashboard] do
        collection do
          post :dashboard
        end
      end
      get 'brands', to: 'templates#get_brand_names'
      get 'emirates', to: 'templates#get_emirate_names'
      get 'brands/:id', to: 'templates#get_model_names'
      post 'profile_data', to: 'templates#get_profile_data'
      post 'search', to: 'ads#search'
    end
  end

  resources :brands do
    collection do
      get 'get_brands_from_category'
    end
  end

  resources :vehicle_models do
    collection do
      get 'get_vehicle_models_from_brand'
    end
  end

end

app/views/shared/_footer.html.erb
<div class="footer" id="footer">
	<div class="container">
		<ul class=" pull-left navbar-link footer-nav">
			<li>
				<a href="<%= root_path %>"> Home </a>
				<a href="<%= about_us_path %>"> About us </a>
				<a href="<%= site_tos_path %>"> Terms and Conditions </a>
				<a href="<%= privacy_policy_path %>"> Privacy Policy </a>
				<a href="<%= contact_us_path %>"> Contact us </a>
				<a href="<%= faq_path %>"> FAQ </a>
			</li>
		</ul>
	</div>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <nav class="navbar   navbar-site navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        <a href="<%= root_path %>" class="navbar-brand logo logo-title">
        <span class="logo-icon"><%= image_tag 'mb_logo.png', :alt => "Motobaba", :width => 60, :height => 60, :title => "Motobaba" %></i> </span> MOTO<span>BABA </span> </a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          </li>
          <li>
          <%= link_to('Dashboard', users_dashboard_path, :method => :get) %>
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_user_session_path)  %>
          </li>
          <li><a href="<%= new_user_registration_path %>">Signup</a></li>
        <% end %>
          <li class="postadd"><a class="btn btn-block   btn-border btn-post btn-danger" href="<%= new_ad_path %>" data-no-turbolink >Post Free Add</a></li>
        </ul>
      </div>
    </div>
  </nav>
</div>