config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/dashboard'

  devise_for :users
  get 'home/index'
  get 'home/get_models_from_brand'
  get 'about_us' => 'home#about_us', :as => :about_us
  get 'contact_us' => 'home#contact', :as => :contact_us
  get 'faq' => 'home#faq', :as => :faq
  get 'privacy' => 'home#privacy_policy', :as => :privacy_policy
  get 'tos' => 'home#tos', :as => :site_tos
  post 'enquiry_mail' => 'home#enquiry_mail'

  resources :users do
    collection do
      get 'myads'
      get 'pending_approval_ads'
      get 'saved_ads'
      put 'remove_saved_ad'
    end
  end

  resources :ads do
    collection do
      get 'get_model'
      get 'model_to_variants'
      get 'success'
      post 'email_to_seller'
      post 'save_ad'
      get :compare
    end
    member do
      get 'tag_spam'
    end
  end

  resources :shortlists do
    member do
      post 'add_ad'
    end
  end

  get 'title_list' => 'ads#title_list'
  get 'location_list' => 'ads#location_list'
  get 'category_list' => 'ads#category_list'

  namespace :api do
    namespace :v1 do
      devise_for :users
      resources :ads, only: [:index, :create] do
        collection do
          post 'show_ad', to: 'ads#show'
        end
        delete :destroy
      end
      resources :users, only: [:dashboard] do
        collection do
          post :dashboard
        end
      end
      get 'brands', to: 'templates#get_brand_names'
      get 'emirates', to: 'templates#get_emirate_names'
      get 'brands/:id', to: 'templates#get_model_names'
      post 'profile_data', to: 'templates#get_profile_data'
      post 'search', to: 'ads#search'
    end
  end

  resources :brands do
    collection do
      get 'get_brands_from_category'
    end
  end

  resources :vehicle_models do
    collection do
      get 'get_vehicle_models_from_brand'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @emirates = Emirate.all
    @models = Brand.first.vehicle_models
  end

  def about_us
  end

  def privacy_policy
  end


  def tos
  end

  def contact
  end

  def faq
  end

  def get_models_from_brand
    models = VehicleModel.where(brand_id: params[:brand])
    render json: models.as_json(only: [:id, :name])
  end

  def enquiry_mail
    UserMailer.enquiry_mail(params[:first_name],params[:last_name],params[:company_name],params[:email],params[:message]).deliver_now
    redirect_to contact_us_path, :notice => 'Successfully sent your message'
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_us.html.erb
<div class="intro-inner">
  <div class="about-intro" style="
  background:url(<%= asset_path 'bg2.jpg' %>) no-repeat center;
  background-size:cover;">
  <div class="dtable hw100">
    <div class="dtable-cell hw100">
      <div class="container text-center">
        <h1 class="intro-title animated fadeInDown"> Building great vehicle market ! </h1>
      </div>
    </div>
  </div>
</div>

</div>

<div class="main-container inner-page">
  <div class="container">
    <div class="section-content">
      <div class="row ">
        <h1 class="text-center title-1"> What Makes Us Special </h1>
        <hr class="center-block small text-hr">
        <div class="col-sm-6">
          <div class="text-content has-lead-para text-left">
            <p class="lead">Howdy ? We are a group of  motor vehicle enthusiasts, we created this platform to help sellers and buyers to meet and do business. We sense that UAE lacked a better open platform for motor vehicle where everybody can sell, buy and contribute. </p>
            <p class="lead">This is our first venture as a company, Motobaba helps you to find sellers for your vehicle and also getting an awesome car for your budget at ZERO cost. Motobaba offers free local classified ads in UAE. Motobaba is the next generation of free online classifieds. </p>
            <p class="lead"> You can post your ads about vechicle which will attract buyers from all around UAE, leading to a perfect sell. All you need to do is click "Post Free Ad" button and follow simple steps.</p>
            <p class="lead"> We provide elegant solutions to buyers as well, including safe buy, free checkups and more. We try our best to ensure that you enjoy a happy and safe market place.</p>
          </div>
        </div>
        <div class="col-sm-6"> <img src="<%= asset_path 'info.png' %>" alt="imfo" class="img-responsive"> </div>
      </div>
    </div>
  </div>
</div>

<div class="parallaxbox about-parallax-bottom">
  <div class="container">
    <div class="row text-center featuredbox">
      <div class="col-sm-4 xs-gap">
        <div class="inner">
          <div class="icon-box-wrap"> <i class="icon-book-open ln-shadow-box shape-3"></i></div>
          <h3 class="title-4">Customer service</h3>
          <p>We've 24/7 email support for customer queries and help. Any problem/issue in site ? shoot us a mail and we'll take care of rest ! We are available at admin@mmotobaba.com</p>
        </div>
      </div>
      <div class="col-sm-4 xs-gap">
        <div class="inner">
          <div class="icon-box-wrap"> <i class=" icon-lightbulb ln-shadow-box shape-6"></i></div>
          <h3 class="title-4">Seller satisfaction</h3>
          <p>Sellers are important part of our website, apart from email support we offer 24/7 phone support for verified sellers. As a verified seller you are able to showcase your ad at featured places, receive offers and more.</p>
        </div>
      </div>
      <div class="col-sm-4 xs-gap">
        <div class="inner">
          <div class="icon-box-wrap"> <i class="icon-megaphone ln-shadow-box shape-5"></i></div>
          <h3 class="title-4">Best Offers </h3>
          <p>As a part of site promotion, we run various promotional contests at random occations, visit every day and stay connected to get exciting offers and gifts. </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/contact.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <div class="intro-inner">
    <div class="contact-intro">
      <div class="w100 map">
        <iframe frameborder="0" height="350" src=
        "https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d26081603.294420466!2d-95.677068!3d37.06250000000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2s!4v1423809000824"
        style="border:0" width="100%"></iframe>
      </div>
    </div>
  </div>
  <div class="main-container">
    <div class="container">
      <div class="row clearfix">
        <div class="col-md-4">
          <div class="contact_info">
            <h5 class="list-title gray"><strong>Contact us</strong></h5>
            <div class="social-list">
              <a href="https://twitter.com/" target="_blank"><i class=
              "fa fa-twitter fa-lg"></i></a> <a href=
              "https://www.facebook.com/" target="_blank"><i class=
              "fa fa-facebook fa-lg"></i></a> <a href="https://plus.google.com"
              target="_blank"><i class="fa fa-google-plus fa-lg"></i></a>
              <a href="https://www.pinterest.com/" target="_blank"><i class=
              "fa fa-pinterest fa-lg"></i></a>
            </div>
          </div>
        </div>
        <div class="col-md-8">
          <div class="contact-form">
            <h5 class="list-title gray"><strong>Contact us</strong></h5>
            <!-- <form class="form-horizontal" method="post"> -->
            <%= form_tag 'enquiry_mail',class:"form-horizontal" do |f| %>
<fieldset>
                <div class="row">
                  <div class="col-sm-6">
                    <div class="form-group">
                      <div class="col-md-12">
                        <input class="form-control" id="firstname" name="first_name"
                        placeholder="First Name" type="text" required>
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group">
                      <div class="col-md-12">
                        <input class="form-control" id="lastname" name="last_name"
                        placeholder="Last Name" type="text">
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group">
                      <div class="col-md-12">
                        <input class="form-control" id="companyname" name=
                        "company_name" placeholder="Company Name" type="text">
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group">
                      <div class="col-md-12">
                        <input class="form-control" id="email" name="email"
                        placeholder="Email Address" type="email" required>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-12">
                    <div class="form-group">
                      <div class="col-md-12">
                        <textarea class="form-control" id="message" name=
                        "message" placeholder=
                        "Enter your massage for us here. We will get back to you within 2 business days."
                        rows="7" required>
</textarea>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="col-md-12">
                        <button class="btn btn-primary btn-lg" type=
                        "submit">Submit</button>
                      </div>
                    </div>
                  </div>
                </div>
              </fieldset>
            <!-- </form> -->
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/home/faq.html.erb
  <div class="intro-inner">
    <div class="about-intro" style=
    "background:url(<%= asset_path 'bg2.jpg' %>) no-repeat center; background-size:cover;">
    <div class="dtable hw100">
        <div class="dtable-cell hw100">
          <div class="container text-center">
            <h1 class="intro-title animated fadeInDown">Frequently Asked
            Questions</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main-container inner-page">
    <div class="container">
      <div class="section-content">
        <div class="row">
          <h1 class="text-center title-1">classified ads
          <strong>FAQ</strong></h1>
          <hr class="center-block small text-hr">
        </div>
        <div class="faq-content">
          <div aria-multiselectable="true" class="panel-group faq-panel" id=
          "accordion" role="tablist">
            <div class="panel">
              <div class="panel-heading" id="headingOne" role="tab">
                <h4 class="panel-title"><a aria-controls="collapseOne"
                aria-expanded="true" data-parent="#accordion" data-toggle=
                "collapse" href="#collapseOne">How do I place an ad?</a></h4>
              </div>
              <div aria-labelledby="headingOne" class=
              "panel-collapse collapse in" id="collapseOne" role="tabpanel">
                <div class="panel-body">
                Click on "Post Free Ad" button on top-right corner, if you are not logged in you should login. Follow simple procedure to post your free ad.
                </div>
              </div>
            </div>
            <div class="panel">
              <div class="panel-heading" id="headingTwo" role="tab">
                <h4 class="panel-title"><a aria-controls="collapseTwo"
                aria-expanded="false" class="collapsed" data-parent=
                "#accordion" data-toggle="collapse" href="#collapseTwo">What
                does it cost to advertise?</a></h4>
              </div>
              <div aria-labelledby="headingTwo" class="panel-collapse collapse"
              id="collapseTwo" role="tabpanel">
                <div class="panel-body">
                We believe in a open platform where everybody can pool in, it's absolutely free to post Ads in Motobaba.com. Well, we are planning to add some featured plans soon.
                </div>
              </div>
            </div>
            <div class="panel">
              <div class="panel-heading" id="headingThree" role="tab">
                <h4 class="panel-title"><a aria-controls="collapseThree"
                aria-expanded="false" class="collapsed" data-parent=
                "#accordion" data-toggle="collapse" href="#collapseThree">If I
                post an ad, will I also get more spam e-mails?</a></h4>
              </div>
              <div aria-labelledby="headingThree" class=
              "panel-collapse collapse" id="collapseThree" role="tabpanel">
                <div class="panel-body">
                  No, you won't get any SPAM mails from us or any of our assosiates. if you are very sensitive about email, you could hide your email while posting ads, we give every privacy option possible to make your experiance better.
                </div>
              </div>
            </div>
            <div class="panel">
              <div class="panel-heading" id="heading_04" role="tab">
                <h4 class="panel-title"><a aria-controls="collapse_04"
                aria-expanded="false" class="collapsed" data-parent=
                "#accordion" data-toggle="collapse" href="#collapse_04">How
                long will my ad remain on the website?</a></h4>
              </div>
              <div aria-labelledby="heading_04" class="panel-collapse collapse"
              id="collapse_04" role="tabpanel">
                <div class="panel-body">
                  Your ad will last on Motobaba untill you delete it, there isn't a expiration period for advertisements even it's free.
                </div>
              </div>
            </div>
            <div class="panel">
              <div class="panel-heading" id="heading_05" role="tab">
                <h4 class="panel-title"><a aria-controls="collapse_05"
                aria-expanded="false" class="collapsed" data-parent=
                "#accordion" data-toggle="collapse" href="#collapse_05">I sold
                my item. How do I delete my ad?</a></h4>
              </div>
              <div aria-labelledby="heading_05" class="panel-collapse collapse"
              id="collapse_05" role="tabpanel">
                <div class="panel-body">
                  You could make your ad status as "Sold out", so it won't appear on ad listing or anywhere seller searches, also you could delete it if wanted, choice is yours.
                </div>
              </div>
            </div>
            <div class="panel">
              <div class="panel-heading" id="heading_06" role="tab">
                <h4 class="panel-title"><a aria-controls="collapse_06"
                aria-expanded="false" class="collapsed" data-parent=
                "#accordion" data-toggle="collapse" href="#collapse_06">How do I contact you ?</a></h4>
              </div>
              <div aria-labelledby="heading_06" class="panel-collapse collapse"
              id="collapse_06" role="tabpanel">
                <div class="panel-body">
                  Git stuck somewhere ? Need any help ? Shoot a mail admin@motobaba.com, we'll be available 24/7.
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="parallaxbox about-parallax-bottom">
    <div class="container">
      <div class="row text-center featuredbox">
        <div class="col-sm-4 xs-gap">
          <div class="inner">
            <div class="icon-box-wrap">
              <i class="icon-book-open ln-shadow-box shape-3"></i>
            </div>
            <h3 class="title-4">Customer service</h3>
            <p>We've 24/7 email support for customer queries and help. Any problem/issue in site ? shoot us a mail and we'll take care of rest ! We are available at admin@mmotobaba.com</p>
          </div>
        </div>
        <div class="col-sm-4 xs-gap">
          <div class="inner">
            <div class="icon-box-wrap">
              <i class=" icon-lightbulb ln-shadow-box shape-2"></i>
            </div>
            <h3 class="title-4">Seller satisfaction</h3>
            <p>Sellers are important part of our website, apart from email support we offer 24/7 phone support for verified sellers. As a verified seller you are able to showcase your ad at featured places, receive offers and more.</p>
          </div>
        </div>
        <div class="col-sm-4 xs-gap">
          <div class="inner">
            <div class="icon-box-wrap">
              <i class="icon-megaphone ln-shadow-box shape-7"></i>
            </div>
            <h3 class="title-4">Best Offers</h3>
            <p>As a part of site promotion, we run various promotional contests at random occations, visit every day and stay connected to get exciting offers and gifts.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/home/index.html.erb
<div class="intro">
	<div class="dtable hw100">
		<div class="dtable-cell hw100">
			<div class="container text-center">
        <%= form_tag ads_path, method: 'GET'  do %>
  				<h1 class="intro-title animated fadeInDown"> Buy/Sell your vechicle </h1>
  				<p class="sub animateme fittext3 animated fadeIn"> Want to sell/buy a car ? don't think twice, just post an ad. </p>
          <div class="row search-row animated fadeInUp">
            <div class="col-lg-3 col-sm-4 search-col relative locationicon">
              <i class="icon-location-2 icon-append"></i>
              <%= select_tag :emirate, options_from_collection_for_select(Emirate.all, 'id', 'name'), prompt: 'All City', class: 'form-control locinput input-rel searchtag-input has-icon' %>
            </div>
            <div class="col-lg-3 col-sm-4 search-col relative"> <i class="icon-docs icon-append"></i>
              <%= select_tag :brand, options_from_collection_for_select(Brand.all, 'id', 'name'), prompt: 'All Make', class: 'form-control locinput input-rel searchtag-input has-icon' %>
            </div>
            <div class="col-lg-3 col-sm-4 search-col relative"> <i class="icon-docs icon-append"></i>
              <%= select_tag :model, options_from_collection_for_select(@models, 'id', 'name'), prompt: 'All Model', class: 'form-control locinput input-rel searchtag-input has-icon' %>
            </div>
            <div class="col-lg-3 col-sm-4 search-col">
              <button class="btn btn-primary btn-search btn-block"><i class="icon-search"></i><strong>Find</strong></button>
            </div>
          </div>
        <% end %>
			</div>
		</div>
	</div>
</div>


<div class="page-info" style="background: url(<%= asset_path('bottom_image.jpg') %>); background-size:cover">
  <div class="container text-center section-promo">
     <div class="row">
        <div class="col-sm-3 col-xs-6 col-xxs-12">
           <div class="iconbox-wrap">
              <div class="iconbox">
                 <div class="iconbox-wrap-icon">
                    <i class="icon  icon-group"></i>
                 </div>
                 <div class="iconbox-wrap-content">
                    <h5><span>1,000+</span> </h5>
                    <div class="iconbox-wrap-text">Trusted users</div>
                 </div>
              </div>
           </div>
        </div>
        <div class="col-sm-3 col-xs-6 col-xxs-12">
           <div class="iconbox-wrap">
              <div class="iconbox">
                 <div class="iconbox-wrap-icon">
                    <i class="icon  icon-th-large-1"></i>
                 </div>
                 <div class="iconbox-wrap-content">
                    <h5><span>1,000+</span> </h5>
                    <div class="iconbox-wrap-text">Ads</div>
                 </div>
              </div>
           </div>
        </div>
        <div class="col-sm-3 col-xs-6  col-xxs-12">
           <div class="iconbox-wrap">
              <div class="iconbox">
                 <div class="iconbox-wrap-icon">
                    <i class="icon  icon-map"></i>
                 </div>
                 <div class="iconbox-wrap-content">
                    <h5><span>7+</span> </h5>
                    <div class="iconbox-wrap-text">Cities</div>
                 </div>
              </div>
           </div>
        </div>
        <div class="col-sm-3 col-xs-6 col-xxs-12">
           <div class="iconbox-wrap">
              <div class="iconbox">
                 <div class="iconbox-wrap-icon">
                    <i class="icon icon-facebook"></i>
                 </div>
                 <div class="iconbox-wrap-content">
                    <h5><span>10,000+</span> </h5>
                    <div class="iconbox-wrap-text"> Facebook Fans</div>
                 </div>
              </div>
           </div>
        </div>
     </div>
  </div>
</div>